<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>rids_introspector</name>
  <version>0.2.0</version>
  <description>Real-time ROS 2 graph introspection module that monitors active nodes, topics, and network topology for RIDS.</description>
  <maintainer email="sromerovalderas@gmail.com">Sergi Romero</maintainer>
  <license>MIT</license>

  <depend>python3-scapy</depend>
  <depend>python3-networkx</depend>
  <depend>python3-matplotlib</depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
