version: 1
created_at: '2026-09-04T20:22:36Z'
source: turtlesim
critical_topics: []
participants:
- 01:0f:39:63:52:8c:9b:2c:00:00:00:00
- 01:0f:39:63:60:5d:aa:0c:00:00:00:00
- 01:0f:39:63:c1:70:ee:9e:00:00:00:00
- 01:0f:39:63:eb:70:d0:7e:00:00:00:00
endpoints:
- guid: 01:0f:39:63:60:5d:aa:0c:00:00:00:00:00:00:03:03
  participant: 01:0f:39:63:60:5d:aa:0c:00:00:00:00
  topic: /rosout
  role: publisher
  type_name: rcl_interfaces::msg::dds_::Log_
  qos:
    reliability: RELIABLE
    durability: TRANSIENT_LOCAL
- guid: 01:0f:39:63:60:5d:aa:0c:00:00:00:00:00:00:04:03
  participant: 01:0f:39:63:60:5d:aa:0c:00:00:00:00
  topic: /parameter_events
  role: publisher
  type_name: rcl_interfaces::msg::dds_::ParameterEvent_
  qos:
    reliability: RELIABLE
    durability: VOLATILE
- guid: 01:0f:39:63:c1:70:ee:9e:00:00:00:00:00:00:03:03
  participant: 01:0f:39:63:c1:70:ee:9e:00:00:00:00
  topic: /rosout
  role: publisher
  type_name: rcl_interfaces::msg::dds_::Log_
  qos:
    reliability: RELIABLE
    durability: TRANSIENT_LOCAL
- guid: 01:0f:39:63:c1:70:ee:9e:00:00:00:00:00:00:04:04
  participant: 01:0f:39:63:c1:70:ee:9e:00:00:00:00
  topic: /talker/get_parametersRequest
  role: subscriber
  type_name: rcl_interfaces::srv::dds_::GetParameters_Request_
  qos:
    reliability: RELIABLE
    durability: VOLATILE
- guid: 01:0f:39:63:c1:70:ee:9e:00:00:00:00:00:00:05:03
  participant: 01:0f:39:63:c1:70:ee:9e:00:00:00:00
  topic: /talker/get_parametersReply
  role: publisher
  type_name: rcl_interfaces::srv::dds_::GetParameters_Response_
  qos:
    reliability: RELIABLE
    durability: VOLATILE
- guid: 01:0f:39:63:c1:70:ee:9e:00:00:00:00:00:00:06:04
  participant: 01:0f:39:63:c1:70:ee:9e:00:00:00:00
  topic: /talker/get_parameter_typesRequest
  role: subscriber
  type_name: rcl_interfaces::srv::dds_::GetParameterTypes_Request_
  qos:
    reliability: RELIABLE
    durability: VOLATILE
- guid: 01:0f:39:63:c1:70:ee:9e:00:00:00:00:00:00:07:03
  participant: 01:0f:39:63:c1:70:ee:9e:00:00:00:00
  topic: /talker/get_parameter_typesReply
  role: publisher
  type_name: rcl_interfaces::srv::dds_::GetParameterTypes_Response_
  qos:
    reliability: RELIABLE
    durability: VOLATILE
- guid: 01:0f:39:63:c1:70:ee:9e:00:00:00:00:00:00:08:04
  participant: 01:0f:39:63:c1:70:ee:9e:00:00:00:00
  topic: /talker/set_parametersRequest
  role: subscriber
  type_name: rcl_interfaces::srv::dds_::SetParameters_Request_
  qos:
    reliability: RELIABLE
    durability: VOLATILE
- guid: 01:0f:39:63:c1:70:ee:9e:00:00:00:00:00:00:09:03
  participant: 01:0f:39:63:c1:70:ee:9e:00:00:00:00
  topic: /talker/set_parametersReply
  role: publisher
  type_name: rcl_interfaces::srv::dds_::SetParameters_Response_
  qos:
    reliability: RELIABLE
    durability: VOLATILE
- guid: 01:0f:39:63:c1:70:ee:9e:00:00:00:00:00:00:0a:04
  participant: 01:0f:39:63:c1:70:ee:9e:00:00:00:00
  topic: /talker/set_parameters_atomicallyRequest
  role: subscriber
  type_name: rcl_interfaces::srv::dds_::SetParametersAtomically_Request_
  qos:
    reliability: RELIABLE
    durability: VOLATILE
- guid: 01:0f:39:63:c1:70:ee:9e:00:00:00:00:00:00:0b:03
  participant: 01:0f:39:63:c1:70:ee:9e:00:00:00:00
  topic: /talker/set_parameters_atomicallyReply
  role: publisher
  type_name: rcl_interfaces::srv::dds_::SetParametersAtomically_Response_
  qos:
    reliability: RELIABLE
    durability: VOLATILE
- guid: 01:0f:39:63:c1:70:ee:9e:00:00:00:00:00:00:0c:04
  participant: 01:0f:39:63:c1:70:ee:9e:00:00:00:00
  topic: /talker/describe_parametersRequest
  role: subscriber
  type_name: rcl_interfaces::srv::dds_::DescribeParameters_Request_
  qos:
    reliability: RELIABLE
    durability: VOLATILE
- guid: 01:0f:39:63:c1:70:ee:9e:00:00:00:00:00:00:0d:03
  participant: 01:0f:39:63:c1:70:ee:9e:00:00:00:00
  topic: /talker/describe_parametersReply
  role: publisher
  type_name: rcl_interfaces::srv::dds_::DescribeParameters_Response_
  qos:
    reliability: RELIABLE
    durability: VOLATILE
- guid: 01:0f:39:63:c1:70:ee:9e:00:00:00:00:00:00:0e:04
  participant: 01:0f:39:63:c1:70:ee:9e:00:00:00:00
  topic: /talker/list_parametersRequest
  role: subscriber
  type_name: rcl_interfaces::srv::dds_::ListParameters_Request_
  qos:
    reliability: RELIABLE
    durability: VOLATILE
- guid: 01:0f:39:63:c1:70:ee:9e:00:00:00:00:00:00:11:04
  participant: 01:0f:39:63:c1:70:ee:9e:00:00:00:00
  topic: /parameter_events
  role: subscriber
  type_name: rcl_interfaces::msg::dds_::ParameterEvent_
  qos:
    reliability: RELIABLE
    durability: VOLATILE
- guid: 01:0f:39:63:c1:70:ee:9e:00:00:00:00:00:00:12:04
  participant: 01:0f:39:63:c1:70:ee:9e:00:00:00:00
  topic: /talker/get_type_descriptionRequest
  role: subscriber
  type_name: type_description_interfaces::srv::dds_::GetTypeDescription_Request_
  qos:
    reliability: RELIABLE
    durability: VOLATILE
- guid: 01:0f:39:63:eb:70:d0:7e:00:00:00:00:00:00:03:03
  participant: 01:0f:39:63:eb:70:d0:7e:00:00:00:00
  topic: /rosout
  role: publisher
  type_name: rcl_interfaces::msg::dds_::Log_
  qos:
    reliability: RELIABLE
    durability: TRANSIENT_LOCAL
- guid: 01:0f:39:63:eb:70:d0:7e:00:00:00:00:00:00:04:04
  participant: 01:0f:39:63:eb:70:d0:7e:00:00:00:00
  topic: /listener/get_parametersRequest
  role: subscriber
  type_name: rcl_interfaces::srv::dds_::GetParameters_Request_
  qos:
    reliability: RELIABLE
    durability: VOLATILE
- guid: 01:0f:39:63:eb:70:d0:7e:00:00:00:00:00:00:05:03
  participant: 01:0f:39:63:eb:70:d0:7e:00:00:00:00
  topic: /listener/get_parametersReply
  role: publisher
  type_name: rcl_interfaces::srv::dds_::GetParameters_Response_
  qos:
    reliability: RELIABLE
    durability: VOLATILE
- guid: 01:0f:39:63:eb:70:d0:7e:00:00:00:00:00:00:06:04
  participant: 01:0f:39:63:eb:70:d0:7e:00:00:00:00
  topic: /listener/get_parameter_typesRequest
  role: subscriber
  type_name: rcl_interfaces::srv::dds_::GetParameterTypes_Request_
  qos:
    reliability: RELIABLE
    durability: VOLATILE
- guid: 01:0f:39:63:eb:70:d0:7e:00:00:00:00:00:00:07:03
  participant: 01:0f:39:63:eb:70:d0:7e:00:00:00:00
  topic: /listener/get_parameter_typesReply
  role: publisher
  type_name: rcl_interfaces::srv::dds_::GetParameterTypes_Response_
  qos:
    reliability: RELIABLE
    durability: VOLATILE
- guid: 01:0f:39:63:eb:70:d0:7e:00:00:00:00:00:00:08:04
  participant: 01:0f:39:63:eb:70:d0:7e:00:00:00:00
  topic: /listener/set_parametersRequest
  role: subscriber
  type_name: rcl_interfaces::srv::dds_::SetParameters_Request_
  qos:
    reliability: RELIABLE
    durability: VOLATILE
- guid: 01:0f:39:63:eb:70:d0:7e:00:00:00:00:00:00:09:03
  participant: 01:0f:39:63:eb:70:d0:7e:00:00:00:00
  topic: /listener/set_parametersReply
  role: publisher
  type_name: rcl_interfaces::srv::dds_::SetParameters_Response_
  qos:
    reliability: RELIABLE
    durability: VOLATILE
- guid: 01:0f:39:63:eb:70:d0:7e:00:00:00:00:00:00:0a:04
  participant: 01:0f:39:63:eb:70:d0:7e:00:00:00:00
  topic: /listener/set_parameters_atomicallyRequest
  role: subscriber
  type_name: rcl_interfaces::srv::dds_::SetParametersAtomically_Request_
  qos:
    reliability: RELIABLE
    durability: VOLATILE
- guid: 01:0f:39:63:eb:70:d0:7e:00:00:00:00:00:00:0b:03
  participant: 01:0f:39:63:eb:70:d0:7e:00:00:00:00
  topic: /listener/set_parameters_atomicallyReply
  role: publisher
  type_name: rcl_interfaces::srv::dds_::SetParametersAtomically_Response_
  qos:
    reliability: RELIABLE
    durability: VOLATILE
- guid: 01:0f:39:63:eb:70:d0:7e:00:00:00:00:00:00:0c:04
  participant: 01:0f:39:63:eb:70:d0:7e:00:00:00:00
  topic: /listener/describe_parametersRequest
  role: subscriber
  type_name: rcl_interfaces::srv::dds_::DescribeParameters_Request_
  qos:
    reliability: RELIABLE
    durability: VOLATILE
- guid: 01:0f:39:63:eb:70:d0:7e:00:00:00:00:00:00:0d:03
  participant: 01:0f:39:63:eb:70:d0:7e:00:00:00:00
  topic: /listener/describe_parametersReply
  role: publisher
  type_name: rcl_interfaces::srv::dds_::DescribeParameters_Response_
  qos:
    reliability: RELIABLE
    durability: VOLATILE
- guid: 01:0f:39:63:eb:70:d0:7e:00:00:00:00:00:00:0e:04
  participant: 01:0f:39:63:eb:70:d0:7e:00:00:00:00
  topic: /listener/list_parametersRequest
  role: subscriber
  type_name: rcl_interfaces::srv::dds_::ListParameters_Request_
  qos:
    reliability: RELIABLE
    durability: VOLATILE
- guid: 01:0f:39:63:eb:70:d0:7e:00:00:00:00:00:00:0f:03
  participant: 01:0f:39:63:eb:70:d0:7e:00:00:00:00
  topic: /listener/list_parametersReply
  role: publisher
  type_name: rcl_interfaces::srv::dds_::ListParameters_Response_
  qos:
    reliability: RELIABLE
    durability: VOLATILE
- guid: 01:0f:39:63:eb:70:d0:7e:00:00:00:00:00:00:10:03
  participant: 01:0f:39:63:eb:70:d0:7e:00:00:00:00
  topic: /parameter_events
  role: publisher
  type_name: rcl_interfaces::msg::dds_::ParameterEvent_
  qos:
    reliability: RELIABLE
    durability: VOLATILE
- guid: 01:0f:39:63:eb:70:d0:7e:00:00:00:00:00:00:11:04
  participant: 01:0f:39:63:eb:70:d0:7e:00:00:00:00
  topic: /parameter_events
  role: subscriber
  type_name: rcl_interfaces::msg::dds_::ParameterEvent_
  qos:
    reliability: RELIABLE
    durability: VOLATILE
- guid: 01:0f:39:63:eb:70:d0:7e:00:00:00:00:00:00:12:04
  participant: 01:0f:39:63:eb:70:d0:7e:00:00:00:00
  topic: /listener/get_type_descriptionRequest
  role: subscriber
  type_name: type_description_interfaces::srv::dds_::GetTypeDescription_Request_
  qos:
    reliability: RELIABLE
    durability: VOLATILE
- guid: 01:0f:39:63:eb:70:d0:7e:00:00:00:00:00:00:13:03
  participant: 01:0f:39:63:eb:70:d0:7e:00:00:00:00
  topic: /listener/get_type_descriptionReply
  role: publisher
  type_name: type_description_interfaces::srv::dds_::GetTypeDescription_Response_
  qos:
    reliability: RELIABLE
    durability: VOLATILE
- guid: 01:0f:39:63:eb:70:d0:7e:00:00:00:00:00:00:14:04
  participant: 01:0f:39:63:eb:70:d0:7e:00:00:00:00
  topic: /chatter
  role: subscriber
  type_name: std_msgs::msg::dds_::String_
  qos:
    reliability: RELIABLE
    durability: VOLATILE
