name: ROS 2 Jazzy CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  ros_ci:
    runs-on: ubuntu-latest
    container:
      image: rostooling/setup-ros-docker:ubuntu-noble-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build and Test ROS 2 Workspace
        uses: ros-tooling/action-ros-ci@v0.4
        with:
          target-ros2-distro: jazzy